### ISSUE TITLE
Issue with the latest version of parse-json dependency

### ISSUE THREAD

**Issue by ELIONET** [lykmapipo/common#7]
Hello,

I am facing an issue which is basically the same as [this one](https://github.com/lykmapipo/common/issues/5) but with the parse-json dependency.

Four days ago, parse-json has been released on version 6.0.0. The package.json of this library includes the following dependency: 
`    "parse-json": ">=5.2.0",`

However, trying to import the parse-json library, the following error is raised:

```Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/node/wks/api/node_modules/parse-json/index.js
require() of ES modules is not supported.
require() of /home/node/wks/api/node_modules/parse-json/index.js from /home/node/wks/api/node_modules/@lykmapipo/common/lib/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/node/wks/api/node_modules/parse-json/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/node/wks/api/node_modules/parse-json/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/node/wks/api/node_modules/@lykmapipo/common/lib/index.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/node/wks/api/node_modules/@lykmapipo/mongoose-common/lib/index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/node/wks/api/node_modules/mongoose-gridfs/lib/index.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
    code: 'ERR_REQUIRE_ESM'
    }
```

Node version : v14.17.0

Forcing the dependency to 5.2.0 version should solve the issue.
`    "parse-json": "5.2.0",`

**Temporary fix (using yarn) :** 

Add the following lines at the end of your package.json file : 
```
  "resolutions": {
    "**/@lykmapipo/common/parse-json": "5.2.0"
  }
```
If you are using the mongoose-gridfs package, you should instead use
```
  "resolutions": {
    "mongoose-gridfs/@lykmapipo/mongoose-common/@lykmapipo/common/parse-json": "5.2.0"
  }
```

More information about `resolutions` : [https://newbedev.com/how-do-i-override-nested-dependencies-with-yarn](https://newbedev.com/how-do-i-override-nested-dependencies-with-yarn)

**Comment by lykmapipo** [comment]
@ELIONET Thanks. Try use latest version `v0.44.5`.
